# Generated by Django 4.0.5 on 2022-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_url',
            field=models.TextField(default='no img'),
        ),
    ]
