# Generated by Django 4.0.5 on 2022-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_alter_artist_name_alter_artist_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='no genre', max_length=100),
        ),
    ]
